version: "3.7"

networks:
  docker.network:
    driver: bridge

services:
  php:
    build: ./docker/php
    restart: unless-stopped
    container_name: docker.php
    tty: true
    depends_on:
      - mysql
    networks:
      - docker.network
    volumes:
      - ./app:/var/www

  nginx:
    build: ./docker/nginx
    container_name: docker.nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php
    ports:
      - "80:80"
    networks:
      - docker.network
    volumes:
      - ./app:/var/www

  mysql:
    image: mysql:latest
    restart: unless-stopped
    container_name: docker.mysql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - docker.network
    volumes:
      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
      - "./docker/mysql/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: symfony-test
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: ruslan

  mysql-test:
    image: mysql:latest
    restart: unless-stopped
    container_name: docker.mysql.test
    tty: true
    ports:
      - "3307:3306"
    networks:
      - docker.network
    environment:
      MYSQL_DATABASE: symfony-test_test
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: ruslan_test

#  mysql-test:
#    image: mysql:latest
#    restart: unless-stopped
#    container_name: docker.mysql
#    tty: true
#    ports:
#      - "3306:3306"
#    networks:
#      - docker.network
#    volumes:
#      - "./docker/mysql/mysql.cnf:/etc/mysql/conf.d/custom.cnf:ro"
#      - "./docker/mysql/dbdata:/var/lib/mysql"
#    environment:
#      MYSQL_DATABASE: symfony-test
#      MYSQL_ROOT_PASSWORD: secret
#      MYSQL_PASSWORD: secret
#      MYSQL_USER: ruslan

  phpmyadmin:
    image: phpmyadmin
    container_name: docker.phpmyadmin
    tty: true
    depends_on:
      - mysql
    ports:
      - "8080:80"
    networks:
      - docker.network
    environment:
      PMA_HOST: mysql
      PMA_ARBITRARY: 1
      PMA_PORT: 3306